FROM amazonlinux:2

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

RUN yum update -y \
    && yum install -y python3 python3-pip \
    && pip3 install --upgrade pipenv setuptools \
    && mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY . .

RUN pipenv install \
	&& pipenv lock -r > requirements.txt \
	&& python3 setup.py install

ENTRYPOINT [ "/usr/local/bin/awsctl" ]

CMD [ "--help" ]
